#!/bin/bash -l
#PBS -l nodes=1:ppn=4
#PBS -N NAME_DFT
#PBS -o quanty.sout
#PBS -e quanty.serr
#PBS -V
cd $PBS_O_WORKDIR

python write_0.py
quanty 0_RunNAMEFPLO.Quanty &> testing_0.out
cp -r DFT/ DFT_backup/
python write_1.py
quanty 1_RunNAMEFPLO_WF.Quanty &> testing_1.out

# Remove +wancoeff, takes up too much space on the drive
rm DFT/+wancoeff

cd "LFMcalc/"
python write_LFMcalc.py
qsub qsub.script
