import sys
sys.path.insert(1,"/home/ccardot3/Python_Code/CharlesFunctions/")
import CharlesFunctions as CF

import numpy as np
import matplotlib.pyplot as plt
import scipy
import datetime
import re
import os

import plot_utils

from pathlib import Path
from matplotlib.ticker import ScalarFormatter

from pymatgen.vis.structure_vtk import StructureVis
from pymatgen.core import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

from PIL import Image

plot_params_dict = {
    "iso": {"color": "black"},
    "z_lin": {"color": "tab:orange"},
    "y_lin": {"color": "tab:green"},
    "x_lin": {"color": "tab:purple"},
    "z_rig": {"color": "blue"},
    "z_lef": {"color": "red"},
    "y_rig": {"color": "blue"},
    "y_lef": {"color": "red"},
    "x_rig": {"color": "blue"},
    "x_lef": {"color": "red"},
}

L23_pp_dict = {
    "left": -5,
    "right": 30,
    "output_filename": "L23_composite.png"
}

crystal_pp_dict = {
    "xdir_filename": "crystal_xdir.png",
    "ydir_filename": "crystal_ydir.png",
    "zdir_filename": "crystal_zdir.png",
}

BSandLDOS_pp_dict = {
    "emin": -10,
    "emax": 10,
    "output_filename": "bs_and_ldos.png"
}

## Material and File Management
# parent_dir should be one directory deeper than the "automation" directory, 
# such as the automation_scratch directory
path_to_file = Path(os.path.realpath(__file__))
automation_index = next((i for i, p in enumerate(path_to_file.parts) if p == 'automation'), None)
parent_dir = path_to_file.parents[len(path_to_file.parts) - automation_index - 3]

NAME = os.getcwd().split("/")[-1]
cif = parent_dir / str("materials/%s/%s.cif" % (NAME,NAME))
structure = Structure.from_file(cif)

import json
with open(parent_dir / str("materials/%s/%s.inp" % (NAME,NAME)),"r") as f:
    material_input = json.load(f)

# Add name to default plot_params
plot_params_dict.update({"NAME": NAME})

## DFT Due Diligence Plots
# SCF Convergence
plot_utils.make_SCFConvPlots("DFT/out.scflow", {"output_filename": "SCFconv_scflow.png"})
plot_utils.make_SCFConvPlots("DFT/out.scf", {"output_filename": "SCFconv_scf.png"})
image_paths = ["SCFconv_scflow.png", "SCFconv_scf.png"]
output_path = "stitched_SCFconv.png"
plot_utils.stitch_images_horizontal(image_paths, output_path)

# Band Structure, Wannier Bands, and LDOS
plot_utils.make_BandStructAndLdosPlots(Path("DFT"), material_input, BSandLDOS_pp_dict)

# L23 XAS Spectra Plots
plot_utils.make_QuantyPlots_XAS("LFMcalc", {**L23_pp_dict, **plot_params_dict})

# Crystal Visualization
plot_utils.make_crystalvisplots(structure, {"direction": "x", "output_filename": "crystal_xdir.png"})
plot_utils.make_crystalvisplots(structure, {"direction": "y", "output_filename": "crystal_ydir.png"})
plot_utils.make_crystalvisplots(structure, {"direction": "z", "output_filename": "crystal_zdir.png"})
image_paths = ["crystal_zdir.png", "crystal_ydir.png", "crystal_xdir.png"]
output_path = "stitched_crystal_image.png"
plot_utils.stitch_images_horizontal(image_paths, output_path)

# Meta Data
text = f"""
METADATA

Plots Generated by: Charles Cardot
Date: {str(datetime.datetime.now())[0:-5]}
System: {NAME}

NOTATION
(axes of propegation, axes of polarization, helicity)
[axes of propegation, dipole, quadrupole]

ex: (z,0,+1) = photon propegating along z-axis with
+1 (right) circular polarization.

"""
plot_utils.text_to_image(text = text, output_path = "header.png", font_size=60)

image_paths = ["header.png", "L23_composite.png"]
image_paths = image_paths + ["stitched_crystal_image.png", "stitched_SCFconv.png", "bs_and_ldos.png"]
output_pdf_path = f"{NAME}_summary.pdf"
plot_utils.convert_images_to_pdf(image_paths, output_pdf_path)
plot_utils.move_png_files(folder_name = f"{NAME}_plots")


